### ISSUE TITLE
Animations not working

### ISSUE THREAD

**Issue by ashokkumar88** [ashvin777/framework7.angular#3]
Hi,

The page transitions are not working. The page is changing without any transition.

**Comment by ashvin777** [comment]
Currently this app framework doesnt support page transition animation. Its in the roadmap.

**Comment by ashvin777** [comment]
Hi Ashok,

I have resolved the animation issue you were seeing in the application by completely changing the architecture of project.  I have written a new plugin for framework7 and angularjs binding. 

This new release doesnt use angularjs router any more and it is using the the Framework7 router now. 

Have a look at the kitchen sink application http://ashvin777.github.io/framework7.angular/kitchen-sink-material/#!/home.html and provide your valuable feedbacks and comments.

Let me know once you are good with this so that I can close this issue.

Thanks You !!

Regards,
Ashvin

**Comment by ashokkumar88** [comment]
HI @ashvin777 ,

You have really done a fantastic job. The animations are working perfectly now. :+1:  Also I can see that you have included jQuery. Is it really required or i can use the built in DOM7 library?

**Comment by ashvin777** [comment]
Hi Ashok,

You can remove jQuery from the app. I have removed the jquery dependency.

Regards,
Ashvin

**Comment by ashokkumar88** [comment]
Thanks.

**Comment by ashvin777** [comment]
Thanks you so much Ashok for your feedback and comments.

Cheers !!
