### ISSUE TITLE
Native transitions

### ISSUE THREAD

**Issue by iMestav** [ashvin777/framework7.angular#9]
Hi,

I want use Native transitions in my app. 

How can i use this plugin https://github.com/Telerik-Verified-Plugins/NativePageTransitions ?

Thanks your answer.

Good work.

**Comment by ashvin777** [comment]
I will check and let you know soon

**Comment by iMestav** [comment]
Thank you.

**Comment by ashvin777** [comment]
As per my study, it looks like that this NativePageTransition plugin is not possible to use for Single Page Applications. Because it loads a new web view for new page while by refreshing the complete DOM. In our case only template html text will be shown in the new view without any bindings and css effects.

**Comment by iMestav** [comment]
Thank you.
